name: "log4u-maven-check"
description: "Checks if a vulnerable Log4u 2 Version is contained in the dependencies of a Maven based project"

inputs:
  token:
    required: false
    description: 'token passed as environment variable GTIHUB_TOKEN to the maven call'
    default: ${{ github.token }}
  project-root:
    description: "the root of the project, default is '.'"
    default: "."
    type: string
    required: false
  settings-path:
    description: "the (optional) path of the settings xml file"
    type: string
    required: false
  multi-module:
    description: "multi-module dependencies need a compile, default ist false"
    type: boolean
    default: false
    required: false
    
runs:
  using: "composite"
  steps:
  - name: evaluate settings parameter
    id: settings-parameter
    shell: bash
    run: |
      if [[ ! -z '${{ inputs.settings-path }}' ]]; then echo "::set-output name=path::-s ${{ inputs.settings-path }}"; fi
  - name: evaluate multi-module parameter
    if: fromJSON(inputs.multi-module)
    id: multi-module
    shell: bash
    run: |
      echo "::set-output name=compile::test-compile -Dmaven.main.skip=true -Dmaven.test.skip=true"

  - name: check log4j dependencies
    shell: bash
    run: |
      cd ${{ inputs.project-root }}
      if LOG4J_DEPENDENCIES=$(mvn --file pom.xml ${{ steps.settings-parameter.outputs.path }} ${{ steps.multi-module.outputs.compile }} dependency:list -Dincludes=org.apache.logging.log4j); then echo "$LOG4J_DEPENDENCIES"; else
        echo "::error failed to check dependencies::$LOG4J_DEPENDENCIES";
        exit -1;
      fi;
      if LOG4J_VERSIONS=$(echo "$LOG4J_DEPENDENCIES" | grep org.apache.logging.log4j | sed -n 's/^.*:jar:\(.*\):.*$/\1/p' | tr '\n' ' '); then echo "success"; else
        LOG4J_VERSIONS=
      fi;
      echo "$LOG4J_VERSIONS"
      for version in $LOG4J_VERSIONS; do
        major=$(echo $version | sed -n 's/^\([0-9]*\)\..*$/\1/p');
        minor=$(echo $version | sed -n 's/^[0-9]*\.\([0-9]*\).*$/\1/p');
        if [[ ($major -eq '1') ]]; then
          echo "::warning title=Detected EOL log4j version $version%2C you should upgrade to at least 2.16, but 2.17 or higher is recommended::Check your dependency tree 'mvn dependency:list -Dincludes=org.apache.logging.log4j'"
        elif [[ ($major -eq '2') && ($minor -lt '16') ]]; then
          echo "::error title=Detected vulnarable log4j version $version::You must upgrade to at least 2.16, but 2.17 or higher is recommended. Check your dependency tree 'mvn dependency:list -Dincludes=org.apache.logging.log4j'"
          exit -1;
        elif [[ ($major -eq '2') && ($minor -eq '16') ]]; then
          echo "::warning title=Detected vulnarable log4j version $version%2C you should upgrade to 2.17 or higher::Check your dependency tree 'mvn dependency:list -Dincludes=org.apache.logging.log4j'"
        fi;
      done;
    env:
      GITHUB_TOKEN: ${{ inputs.token }}

