name: "log4u-maven-check"
description: "Checks if a vulnerable Log4u 2 Version is contained in the dependencies of a Maven based project"

inputs:
  token:
    required: false
    description: 'token passed as environment variable GTIHUB_TOKEN to the maven call'
    default: ${{ github.token }}
  project-root:
    description: "the root of the project, default is '.'"
    default: "."
    type: string
    required: false
  settings-path:
    description: "the (optional) path of the settings xml file"
    type: string
    required: false
    
runs:
  using: "composite"
  steps:
  - name: evaluate settings parameter
    id: settings-parameter
    shell: bash
    run: |
      if [[ ! -z '${{ inputs.settings-path }}' ]]; then echo "::set-output name=path::-s ${{ inputs.settings-path }}"; fi

  - name: check log4j dependencies
    shell: bash
    run: |
      cd ${{ inputs.project-root }}
      echo "1"
      if LOG4J_DEPENDENCIES=$(mvn --file pom.xml ${{ steps.settings-parameter.outputs.path }} dependency:list -Dincludes=org.apache.logging.log4j); then echo "$LOG4J_DEPENDENCIES"; else
        echo "::error failed to check dependencies::$LOG4J_DEPENDENCIES";
        exit -1;
      fi;
      echo "2"
      echo "$LOG4J_DEPENDENCIES" 
      echo "2.1"
      echo "$LOG4J_DEPENDENCIES" | grep org.apache.logging.log4j 
      echo "2.2"
      echo "$LOG4J_DEPENDENCIES" | grep -s org.apache.logging.log4j | sed -n 's/^.*:jar:\(.*\):.*$/\1/p'
      echo "2.3"
      echo "$LOG4J_DEPENDENCIES" | grep -s org.apache.logging.log4j | sed -n 's/^.*:jar:\(.*\):.*$/\1/p' | tr '\n' ' '
      echo "2.4"
      LOG4J_VERSIONS=$(echo "$LOG4J_DEPENDENCIES" | grep -s org.apache.logging.log4j | sed -n 's/^.*:jar:\(.*\):.*$/\1/p' | tr '\n' ' ')
      echo "3"
      echo "$LOG4J_VERSIONS"
      for version in $LOG4J_VERSIONS; do
        echo "3"
        major=$(echo $version | sed -n 's/^\([0-9]*\)\..*$/\1/p');
        minor=$(echo $version | sed -n 's/^[0-9]*\.\([0-9]*\).*$/\1/p');
        echo "4 $major $minor"
        if [[ ($major -eq '1') ]]; then
          echo "::warning title=Detected EOL log4j version $version%2C you should upgrade to at least 2.16::Check your dependency tree 'mvn dependency:list -Dincludes=org.apache.logging.log4j'"
        elif [[ ($major -eq '2') && ($minor -lt '15') ]]; then
          echo "::error title=Detected vulnarable log4j version $version::You must upgrade to at least 2.15%2C2.16 recommended. Check your dependency tree 'mvn dependency:list -Dincludes=org.apache.logging.log4j'"
          exit -1;
        elif [[ ($major -eq '2') && ($minor -eq '15') ]]; then
          echo "::warning title=Detected vulnarable log4j version $version%2C you should upgrade to at least 2.16::Check your dependency tree 'mvn dependency:list -Dincludes=org.apache.logging.log4j'"
        fi;
        echo "5"
      done;
    env:
      GITHUB_TOKEN: ${{ inputs.token }}

